name: Deploy to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests (if applicable)
        run: npm test
      
      - name: Zip artifact for deployment
        run: zip -r functionapp.zip . -x "node_modules/*" "*.git*"
      
      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: functionapp.zip
